# Generated by Django 4.0.6 on 2023-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('email', models.CharField(max_length=300)),
                ('phno', models.CharField(max_length=12)),
                ('services', models.CharField(max_length=600)),
            ],
        ),
    ]
